name: Test

on:
  push:
    branches: "**"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run test
    strategy:
      matrix:
        otp: ["25.3", "26.2", "27.1"]
        elixir: ["1.14.4", "1.17.1"]
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1.17
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Retrieve Cached Dependencies
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
      - name: Check compiler warnings
        run: mix compile --warnings-as-errors --force
      - name: Run Tests
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: mix test --cover
      - name: Check Formatting
        run: mix format --check-formatted
